[dev]
  command = "npm run dev"
  publish = "dist"
  # We need another port for the application because Vite occupies the 3000.

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # We are goint to use ES modules so we need esbuild to transpile the code.
  node_bundler = "esbuild"

# We have to tell the Netlify that this URL will be served by the books.js function.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  conditions = { Path = "/*.(jpg|png|css|js)" }

[[redirects]]
  from = "/assets/*"
  to = "/client/assets/:splat"
  status = 200